### ISSUE TITLE
Update RPC documentation

### ISSUE THREAD

**Issue by yahiheb** [zkSNACKs/WasabiDoc#1601]
**1- Document and update RPC methods.**

Check if all of these PRs have been merged first:

- [x] `recoverwallet`: https://github.com/zkSNACKs/WalletWasabi/pull/11535, https://github.com/zkSNACKs/WalletWasabi/pull/11603 - #1632
- [x] `speeduptransaction`: https://github.com/zkSNACKs/WalletWasabi/pull/11537 - #1635
- [x] `canceltransaction`: https://github.com/zkSNACKs/WalletWasabi/pull/11536 - #1635
- [x] `excludefromcoinjoin`: https://github.com/zkSNACKs/WalletWasabi/pull/11540 -#1640
- [x] `loadwallet`: https://github.com/zkSNACKs/WalletWasabi/pull/11579 - #1639
- [x] `getcoinjoinstatus`: https://github.com/zkSNACKs/WalletWasabi/pull/11559 - #1633
- [x] Add `feeRate` to `build` and `send`: https://github.com/zkSNACKs/WalletWasabi/pull/11667 - #1683
- [x] Update returned values for `getwalletinfo`: https://github.com/zkSNACKs/WalletWasabi/pull/11622 + https://github.com/zkSNACKs/WalletWasabi/pull/11701 - #1633
- [x] `listwallets`: https://github.com/zkSNACKs/WalletWasabi/pull/11701 - #1639
- [x] Update `getstatus`: https://github.com/zkSNACKs/WalletWasabi/pull/11741 - #1667
- [x] Add `payincoinjoin`: https://github.com/zkSNACKs/WalletWasabi/pull/10580#issuecomment-1533631780 - #1629
- [x] Add `listpaymentsincoinjoin`  and `cancelpaymentincoinjoin`: https://github.com/zkSNACKs/WalletWasabi/pull/11976 - #1629
- [x] Add `buildunsafetransaction`: https://github.com/zkSNACKs/WalletWasabi/pull/12124 - #1659

**Comment by yahiheb** [comment]
**2- Document how to expose the RPC Server as an onion service.**

https://github.com/zkSNACKs/WalletWasabi/pull/11714

**Comment by yahiheb** [comment]
All the task of this issue are done.
